version: '3.7'
services:
  postgres:
    container_name: api_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_db
    ports:
      - "5432:5432"
    volumes:
      - api_db:/applis/docker-compose/db/api_db
volumes:
  api_db:
    external: true